version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: babel-plugin-react-css-module-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm i --registry https://registry.npmjs.org
      - run:
          name: Check
          command: npm run ci
      - save_cache:
          key: babel-plugin-react-css-module-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'
